### ISSUE TITLE
I can not edit paragraph after translation

### ISSUE THREAD

**Issue by ava57r** [gitlocalize/feedback#124]
We are translating this file

https://gitlocalize.com/repo/6282/ru/originals/announcements/2022-12-15-Rust-1.66.0.md

paragraph is before

![изображение](https://user-images.githubusercontent.com/20382553/207817949-333a70ee-c8f2-4cb1-a103-e02ebe75a0b5.png)

paragraph is after click

![изображение](https://user-images.githubusercontent.com/20382553/207818102-7216a53e-b6cb-46e1-98a1-6890a32eeecf.png)

**Comment by svasilenkov** [comment]
@ava57r Thank you for the feedback. Unfortunately, we can't reproduce the problem at the moment:

![image](https://user-images.githubusercontent.com/52036683/208468443-2c3cd615-4c82-4fcf-9376-d1194a58f729.png)

Could you please check if GitLocalize still shows original text instead of translated at the moment.

**Comment by ava57r** [comment]
It works. Thanks.
