### ISSUE TITLE
Allow sending reviews before completing all translations

### ISSUE THREAD

**Issue by agektmr** [gitlocalize/feedback#2]
## Background of the problem
When I thought I'm done with translation, there were lots of untranslated text because they were mostly code samples etc. I could only send it for reviews when the completion rate went 100%.

## How to solve the problem, if you have any idea.
I'd like to have an option to send for reviews without completing all translations. I'm fine copying those left over original texts as they are to the translated one.

**Comment by sotayamashita** [comment]
@agektmr We have some request from other users and we are considering it. We will share the opinion by tomorrow. :bow:

**Comment by chikathreesix** [comment]
@agektmr We are very sorry for our late response. Since we originally planned to have a commenting feature on the editor itself to discuss before creating a review request, we designed to allow creating a review request only when it's completed for a final check purpose. But we haven't implemented it yet and we are getting this request from other communities as well, I think this makes sense to enable to create a review request anytime.
Let me look into it this week.
